export angle,
       area,
       are_ordered_along_line, are_strictly_ordered_along_line,
       barycenter,
       bisector,
       centroid,
       circumcenter,
       collinear_are_ordered_along_line,
       collinear_are_strictly_ordered_along_line,
       collinear,
       compare_distance_to_point,
       compare_lexicographically,
       compare_signed_distance_to_line,
       compare_slope,
       compare_squared_distance,
       compare_x, compare_xy, compare_x_at_y,
       compare_y_at_x, compare_y, compare_yx,
       determinant,
       do_intersect,
       has_larger_distance_to_point,
       has_larger_signed_distance_to_line,
       has_smaller_distance_to_point,
       has_smaller_signed_distance_to_line,
       # TODO: intersections
       l_infinity_distance,
       left_turn,
       lexicographically_xy_larger, lexicographically_xy_larger_or_equal,
       lexicographically_xy_smaller, lexicographically_xy_larger_or_smaller,
       max_vertex,
       midpoint,
       min_vertex,
       orientation,
       parallel,
       radical_line,
       rational_rotation_approximation,
       right_turn,
       scalar_product,
       side_of_bounded_circle,
       side_of_oriented_circle,
       squared_distance,
       squared_radius,
       x_equal,
       y_equal,
       do_overlap
